### ISSUE TITLE
2018-XX-XX format not supported

### ISSUE THREAD

**Issue by jerzy-wachowiak** [niklongstone/amazon-date-parser#6]
https://developer.amazon.com/docs/custom-skills/slot-type-reference.html#date

> Utterances that map to a year (such as "next year") convert to a date containing just the year. Note that the date format differs between English and other languages:
 ... 
All other languages (French, German, Italian, Japanese, Portuguese, and Spanish) use the format YYYY-XX-XX. For example: 2018-XX-XX.

2018-XX-XX format is not supported by the library. This is the case if other language then English is used in the Alexa model.

**Comment by niklongstone** [comment]
thanks for reporting.
The library was build when other languagges were not yet supported.
I will add this in the next release.
